name: Pull Request

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    check-version-increase:
        name: Check version tag
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com/
            - run: npx auto pr-check --url https://github.com/$GITHUB_REPOSITORY
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    publish-canary:
        name: Publish a Canary version
        needs: check-version-increase
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com/
                  always-auth: true
                  scope: "@homefully"
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
            - uses: actions/cache@v2
              id: cache-modules
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
            - uses: actions/cache@v2
              if: steps.cache-modules.outputs.cache-hit != 'true'
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-global
            - run: npm ci
              if: steps.cache-modules.outputs.cache-hit != 'true'
              env:
                  NODE_AUTH_TOKEN: ${{secrets.PUBLIC_GH_BOT_TOKEN}}
            - run: npm run build
            - run: npx auto shipit
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_BOT_PUBLISH_SECRET }}
                  GH_TOKEN: ${{ secrets.GH_BOT_PUBLISH_SECRET }}
                  NPM_TOKEN: ${{ secrets.GH_BOT_PUBLISH_SECRET }}
                  NODE_AUTH_TOKEN: ${{secrets.GH_BOT_PUBLISH_SECRET}}
