name: Release new Version

on:
    push:
        branches:
            - "master"
        tags-ignore:
            - "v*"

jobs:
    release-new-version:
        name: Release new version
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
        steps:
            - uses: actions/checkout@main
              with:
                  token: ${{ secrets.PUBLIC_GH_BOT_TOKEN}}
            - name: Prepare repository
              run: |
                  git fetch --unshallow --tags
            - uses: actions/setup-node@main
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com/
                  always-auth: true
                  scope: "@homefully"
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
            - uses: actions/cache@main
              id: cache-modules
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
            - uses: actions/cache@main
              if: steps.cache-modules.outputs.cache-hit != 'true'
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-global
            - run: npm ci
              if: steps.cache-modules.outputs.cache-hit != 'true'
              env:
                  NODE_AUTH_TOKEN: ${{secrets.PUBLIC_GH_BOT_TOKEN}}
            - run: npm run build
            - run: git config --global user.email "bot@homefully.de"
            - run: git config --global user.name "homefully bot"
            - run: npx auto shipit
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_BOT_PUBLISH_SECRET }}
                  NPM_TOKEN: ${{ secrets.GH_BOT_PUBLISH_SECRET }}
                  NODE_AUTH_TOKEN: ${{secrets.GH_BOT_PUBLISH_SECRET}}
